### ISSUE TITLE
[Question] For port maintainers: is there a way to quickly check one port?

### ISSUE THREAD

**Issue by saper** [freebsd/portscout#5]
I ran into this:

````
Port                                            | Current version | New version
------------------------------------------------+-----------------+------------
shells/ksh93                                    | 20141224        | 93v
------------------------------------------------+-----------------+------------
````

https://reviews.freebsd.org/D19343#429876

Since this is my first problem like this, I'd like to quickly test my port's `PORTSCOUT` variable before it gets committed.

Is there a quick way to do this without building a whole portcout infrastructure?

**Comment by koobs** [comment]
@saper Unfortunately not really, but on a positive note, portscout is relatively trivial and quick to install and get running, and you can limit/restrict its runs to only your ports using the maintainer filter. 

@cschuber is right however (in the review comment) that portscout only does very basic checks and doesn't have a comprehensive notion of a ports "version" [1].

See Also: [ports-mgmt/portscout: r405250](http://svnweb.freebsd.org/changeset/ports/405250)
