### ISSUE TITLE
https://portscout.freebsd.org/ not refreshing its data

### ISSUE THREAD

**Issue by smortex** [freebsd/portscout#6]
Last update seems to be 4 days old: the first line of https://portscout.freebsd.org/ says:

```
Last updated on 2019-07-20 at 17:15, by portscout v0.8.1
```

When committing port updates, I am used to see the information being quickly refreshed (have to wait a few minutes / hours to see the changes), but the information of some ports have not been refreshed for days.

**Comment by koobs** [comment]
There were some issues with one PoP for FreeBSD infrastructure which required migrating services. Is the issue still present?

**Comment by smortex** [comment]
@koobs, currently the data seems unchanged:

* https://portscout.freebsd.org/ says Last updated on 2019-07-20 at 17:15
* https://portscout.freebsd.org/puppet@freebsd.org.html still has outdated information (e.g. sysutils/puppet6 is currently at 6.7.2 in the ports tree, while the website says that 6.6.0 is in the tree and 6.7.0 is available).

I guess that if the updating service was down and has been recently restarted, it might still be running and all information will be updated once as a last step of the process?  In this case,it makes sense that the information is still stall, and waiting some more hours would allow the update to complete and make the information available…

**Comment by smortex** [comment]
Just received a reply form zi@ telling me the problem is solved!

Thanks!

**Comment by smortex** [comment]
It seems to be happening again :sob: 

Today, the "Last updated" date seems to be up-to-date but the actual data is stale:

https://portscout.freebsd.org/puppet@freebsd.org.html …is still listing some ports as outdated while they where updated yesterday, e.g. https://www.freshports.org/sysutils/puppetserver6/

(all the ports on this page should be up-to-date as far as I know).

**Comment by smortex** [comment]
Seems to be good now :-)  Closing again!
